import hashlib
import json
import os
import base64
from solders.keypair import Keypair
from solders.pubkey import Pubkey
from solders.system_program import transfer, TransferParams
from solders.transaction import Transaction
from solders.message import Message
from solana.rpc.api import Client
from solana.rpc.types import TxOpts
  
# ── Config ────────────────────────────────────────────────────────────────────
SOLANA_RPC = "https://api.devnet.solana.com"
# Path to your keypair.json generated by solana-keygen
KEYPAIR_PATH = os.environ.get("SOLANA_KEYPAIR_PATH", "keypair.json")
# ─────────────────────────────────────────────────────────────────────────────

def _load_keypair() -> Keypair:
    """Load keypair from JSON file generated by solana-keygen."""
    with open(KEYPAIR_PATH, "r") as f:
        secret = json.load(f)   # list of 64 ints
    return Keypair.from_bytes(bytes(secret))


def hash_report(tracking_id: str, timestamp: str) -> str:
    """
    Creates a SHA-256 hash of the report's tracking ID and timestamp.
    This hash is what gets stored on-chain — no sensitive data touches Solana.
    """
    payload = f"{tracking_id}:{timestamp}"
    return hashlib.sha256(payload.encode()).hexdigest()


def store_hash_on_chain(tracking_id: str, timestamp: str) -> dict:
    """
    Stores a report hash on Solana Devnet using a memo transaction.

    Solana has a built-in Memo program that lets you attach arbitrary
    text (up to 566 bytes) to a transaction. We use this to store
    the SHA-256 hash of the report as a memo — permanently recorded
    on the Solana ledger.

    Returns:
        {
            "success": True,
            "tx_signature": "5Hs...",
            "report_hash": "abc123...",
            "explorer_url": "https://explorer.solana.com/tx/..."
        }
    """
    try:
        client    = Client(SOLANA_RPC)
        keypair   = _load_keypair()
        report_hash = hash_report(tracking_id, timestamp)

        # Memo program ID (Solana built-in)
        MEMO_PROGRAM_ID = Pubkey.from_string(
            "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
        )

        # Build memo instruction — attaches hash as UTF-8 memo
        from solders.instruction import Instruction, AccountMeta
        memo_data = f"cipherdrop:{report_hash}".encode("utf-8")
        memo_ix = Instruction(
            program_id=MEMO_PROGRAM_ID,
            accounts=[
                AccountMeta(pubkey=keypair.pubkey(), is_signer=True, is_writable=False)
            ],
            data=memo_data,
        )

        # Get latest blockhash
        blockhash_resp = client.get_latest_blockhash()
        recent_blockhash = blockhash_resp.value.blockhash

        # Build and sign transaction
        msg = Message.new_with_blockhash(
            [memo_ix],
            keypair.pubkey(),
            recent_blockhash,
        )
        tx = Transaction([keypair], msg, recent_blockhash)

        # Send to devnet
        resp = client.send_transaction(
            tx,
            opts=TxOpts(skip_preflight=False, preflight_commitment="confirmed"),
        )

        tx_sig = str(resp.value)
        return {
            "success":      True,
            "tx_signature": tx_sig,
            "report_hash":  report_hash,
            "explorer_url": f"https://explorer.solana.com/tx/{tx_sig}?cluster=devnet",
        }

    except Exception as e:
        # Blockchain failure should NEVER block a submission
        # Log it and return gracefully
        print(f"[blockchain] WARNING: Failed to store hash on chain: {e}")
        return {
            "success":      False,
            "tx_signature": None,
            "report_hash":  hash_report(tracking_id, timestamp),
            "error":        str(e),
        }


def verify_hash_on_chain(tx_signature: str, tracking_id: str, timestamp: str) -> dict:
    """
    Verifies that a report hash exists on-chain by fetching the transaction
    and comparing the memo data to the expected hash.

    Returns:
        {"verified": True/False, "on_chain_hash": "...", "expected_hash": "..."}
    """
    try:
        client = Client(SOLANA_RPC)
        from solders.signature import Signature

        sig = Signature.from_string(tx_signature)
        tx_resp = client.get_transaction(sig, encoding="json")

        if not tx_resp.value:
            return {"verified": False, "reason": "Transaction not found"}

        # Extract memo from transaction log messages
        log_messages = tx_resp.value.transaction.meta.log_messages or []
        on_chain_hash = None
        for msg in log_messages:
            if "cipherdrop:" in msg:
                on_chain_hash = msg.split("cipherdrop:")[-1].strip().rstrip('"')
                break

        expected_hash = hash_report(tracking_id, timestamp)
        verified = on_chain_hash == expected_hash

        return {
            "verified":      verified,
            "on_chain_hash": on_chain_hash,
            "expected_hash": expected_hash,
        }

    except Exception as e:
        return {"verified": False, "reason": str(e)}
